name: publish-tag
run-name: Add jar to release and publish docker image

on:
  release:
    types: [published]
  push:
    branches:
      - feat_github_actions

jobs:
  publish-artifacts:
    name: Publish jar
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY: eu.gcr.io/contiamo-public/spark-prometheus-export
    steps:
      - name: Check out Repo
        uses: actions/checkout@v3
      - name: Build Image
        run: docker build -t ${DOCKER_REGISTRY}:${GITHUB_REF_NAME} .
      - name: Log Into Registry
        uses: docker/login-action@v1
        with:
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}
          registry: eu.gcr.io
      - name: Push Image
        run: docker push ${DOCKER_REGISTRY}:${GITHUB_REF_NAME}
      - name: Extract Jars
        run: |
          docker image save ${DOCKER_REGISTRY}:${GITHUB_REF_NAME} \
            | tar --extract --wildcards --to-stdout '*/layer.tar' \
            | tar --extract --wildcards 'jars/*.jar'
      - name: Add Jars to Release
        run: |
          # gh release upload $GITHUB_REF jars/*.jar
          gh release upload refs/tags/test-release jars/*.jar
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  